services:
  firmness-api:
    build:
      context: .
      dockerfile: Firmness.Api/Dockerfile
    container_name: firmness-api
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "8081:8080"
    networks:
      - firmness-network

  firmness-webadmin:
    build:
      context: .
      dockerfile: Firmness.WebAdmin/Dockerfile
    container_name: firmness-webadmin
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ApiSettings__BaseUrl=http://firmness-api:8080/api/
      - ApiSettings__PublicBaseUrl=http://localhost:8081
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "8082:8080"
    depends_on:
      - firmness-api
    networks:
      - firmness-network

  firmness-customer:
    build:
      context: Firmness.Customer
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:8081/api
    container_name: firmness-customer
    ports:
      - "8083:80"
    depends_on:
      - firmness-api
    networks:
      - firmness-network

networks:
  firmness-network:
    driver: bridge
